template(name="errorsAndTryCatchTheory")
  p {{_'JavaScript can throw error if something is wrong with code'}}:
  +codeInText
    |var a 'b';

  p {{_'Programmer can throw his own error'}}:
  +codeInText
    |throw new Error('Something wrong happened');
    br
    |console.log('this will not run');
  p {{_'Notice that when we throw error, the code stops executing'}}.
    |{{{_"That's because errors are fatal"}}}.
    |{{{_"When we throw an error, it means that something very bad happened and we want to stop executing the code"}}}.

  p {{_'We can throw an Error from a function'}}.
    |{{{_'In function <b>add</b> in code below, we check if parameter <b>a</b> is not a number (isNaN)'}}}.
    |{{{_'If parameter <b>a</b> is not a number, we throw an error'}}}.
    |{{{_'The same with parameter <b>b</b>'}}}.
  +codeInText
    |function add(a, b) {
    br
    |&#09;if (isNaN(a)) {
    br
    |&#09;&#09;throw new Error('Parameter "a" is not a number');
    br
    |&#09;}
    br
    |&#09;if (isNaN(b)) {
    br
    |&#09;&#09;throw new Error('Parameter "b" is not a number');
    br
    |&#09;}
    br
    |&#09;return a + b;
    br
    |}
    br
    br
    |add('bad parameter', 'also bad parameter');
    br
    |//code on this line won't run
    br
    |//if code above throws an Error
    br
    |add(5, 'bad parameter');

  h3 Try/Catch
  p We can watch for errors in block <b>try</b> and catch errors in block <b>catch</b>:
  +codeInText
    |try {
    br
    |&#09;throw new Error('Something wrong happened');
    br
    |&#09;console.log('this will not run');
    br
    |} catch (err) {
    br
    |&#09;console.log('catching error:');
    br
    |&#09;console.log(err.message);
    br
    |}
  p The <b>try</b> statement lets you test a block of code for errors.
  p The <b>catch</b> statement lets you handle the error.
  p The <b>throw</b> statement lets you create custom errors.
  p If we don't want program to end up with an error, we need to catch the error.
    |If we catch the error, we are able to inform user what's wrong.
    |The <b>catch</b> statement takes one parameter which is an instance of a thrown error.
    |<b>Error</b> object has a property <i>message</i> which usually describes the cause of the error.

  p We can catch errors that are thrown from a function:
  +codeInText
    |function add(a, b) {
    br
    |&#09;if (isNaN(a)) {
    br
    |&#09;&#09;throw new Error('Parameter "a" is not a number');
    br
    |&#09;}
    br
    |&#09;if (isNaN(b)) {
    br
    |&#09;&#09;throw new Error('Parameter "b" is not a number');
    br
    |&#09;}
    br
    |&#09;return a + b;
    br
    |}
    br
    br
    |try {
    br
    |&#09;add('bad parameter', 'also bad parameter');
    br
    |} catch (err) {
    br
    |&#09;console.log('catching error:');
    br
    |&#09;console.log(err.message);
    br
    |}

  p
    span.glyphicon.glyphicon-info-sign
    |Errors in other programming languages are also called <i>exceptions</i>.
